version: '3.8'

services:
  jrnl:
    build: .
    image: jrnl-app:latest
    container_name: jrnl-container
    volumes:
      - ./journal_data:/root/.config/jrnl
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh", "-c"]
    command: ["while true; do sleep 30; done"]